# This playbook illustrates the creation of multiple volumes in async mode.
---
- name: Creation of multiple volumes in a storage group in async mode
  hosts: localhost
  connection: local
  vars:
    unispherehost: 'your_unisphere_host_url'
    universion: "version_of_the_unisphere"
    verifycert: false
    user: 'your_username'
    password: 'your_password'
    serial_no: "your_serial_no"
    sg_name: 'sample_storage_group'
    vol_name: 'sample_volume'
    cap_unit: 'GB'

  tasks:
    - name: Create volume
      register: result
      dellemc.powermax.volume:
        unispherehost: "{{ unispherehost }}"
        universion: "{{ universion }}"
        verifycert: "{{ verifycert }}"
        user: "{{ user }}"
        password: "{{ password }}"
        serial_no: "{{ serial_no }}"
        vol_name: "{{ vol_name + '_' }}{{ item }}"
        sg_name: "{{ sg_name }}"
        size: 1
        cap_unit: "{{ cap_unit }}"
        state: 'present'
      # The creation of multiple volumes in async mode depends on the values of the poll and async. For async=45 and poll=10, the
      # approximate time for the creation of 100 volumes is 30 minutes. Variation in the value of poll and async will affect the volume
      # creation time.
      loop: "{{ range(1, 100 + 1, 1) | list }}"
      async: 45
      poll: 10
