# This example can be used to set a specific PyU4V version.
# If the user wants to use the latest supported version of PyU4V by the collection.
# The `python: -PyU4V == version` does not need to be specified.
# To see the correct version of PyU4V based on your powermax array,
# please checkout our installation guide (https://github.com/dell/ansible-powermax/blob/main/docs/INSTALLATION.md).
dependencies:
  galaxy: |-
    collections:
      - name: dellemc.powermax
        version: x.x.x

# If you want to use a specific PyU4V version other then the latest supported version, please specify below.
# additional_build_steps:
#   append_final:
#     - RUN pip3 uninstall -y PyU4V
#     - RUN pip3 install PyU4V==10.0.0.16
