#  This playbook finds the empty storage groups for a given array.
---
- name: Finding all the empty Storage Groups
  hosts: localhost
  connection: local
  vars:
    unispherehost: 'your_unisphere_host_url'
    verifycert: false
    user: 'your_username'
    password: 'your_password'
    serial_no: "your_serial_no"

  tasks:
  # This task fetches the names of all the storage groups.
    - name: Get names of all the Storage Group
      dellemc.powermax.info:
        unispherehost: "{{ unispherehost }}"
        serial_no: "{{ serial_no }}"
        verifycert: "{{ verifycert }}"
        user: "{{ user }}"
        password: "{{ password }}"
        gather_subset:
          - sg
      register: subset_result

  # The set_fact generates the list of all the storage groups in an array.
    - name: Assign a variable to the list of storage group names
      ansible.builtin.set_fact:
        all_storage_groups_names: "{{ subset_result['StorageGroups'] | list }}"

  # This task gets the details of all the storage groups present in the list all_storage_groups_names.
    - name: Get details of all the Storage Groups
      dellemc.powermax.storagegroup:
        unispherehost: "{{ unispherehost }}"
        verifycert: "{{ verifycert }}"
        user: "{{ user }}"
        password: "{{ password }}"
        serial_no: "{{ serial_no }}"
        sg_name: "{{ item }}"
        state: "present"
      loop: "{{ all_storage_groups_names }}"
      register: all_storage_groups_details

  # The set_fact generates a list of the number of volumes in each storage group.
    - name: Assign a variable to the number of volumes in storage group
      ansible.builtin.set_fact:
        no_of_vols_in_sg: "{{ all_storage_groups_details.results | map(attribute='storage_group_details.num_of_vols') | list }}"

  # This task returns the names of the storage groups which have the zero number of volumes.
    - name: List of all the empty Storage Groups
      ansible.builtin.debug:
        msg: "{{ item.1 }}"
      loop: "{{ no_of_vols_in_sg | zip(all_storage_groups_names) | list }}"
      when: item.0 | int == 0
