# This sample fetches the list of all the Storage Groups names those name contains the search_string

---
- name: List of all the Storage Groups names those name contains the search_string
  hosts: localhost
  connection: local
  vars:
    unispherehost: "your_unisphere_host_url"
    verifycert: false
    user: "your_username"
    password: "your_password"
    serial_no: "your_serial_no"
    search_string: "AnsibleSG"

  tasks:
    - name: List of all the Storage Groups names those name contains the search_string
      dellemc.powermax.info:
        unispherehost: "{{ unispherehost }}"
        serial_no: "{{ serial_no }}"
        verifycert: "{{ verifycert }}"
        user: "{{ user }}"
        password: "{{ password }}"
        gather_subset:
          - sg
        filters:
          - filter_key: "storageGroupId"
            filter_operator: "like"
            filter_value: "{{ search_string }}"
